; This file is for the FamiStudio Sound Engine and was generated by FamiStudio
; Required flags for Escape:

.export _music_data_escape:=music_data_escape

music_data_escape:
	.byte 1
	.word @instruments
	.word @samples-4
; 00 : Symphony of the Well
	.word @song0ch0
	.word @song0ch1
	.word @song0ch2
	.word @song0ch3
	.word @song0ch4
	.byte .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), 2, 0

.export music_data_escape
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env1,@env2,@env3,@env0 ; 00 : Instrument 1

@env0:
	.byte $00,$c0,$7f,$00,$02
@env1:
	.byte $00,$cf,$7f,$00,$02
@env2:
	.byte $c0,$7f,$00,$01
@env3:
	.byte $7f,$00,$00

@samples:

@tempo_env_1_mid:
	.byte $03,$06,$80

@song0ch0:
@song0ch0loop:
	.byte $47, .lobyte(@tempo_env_1_mid), .hibyte(@tempo_env_1_mid), $80
@song0ref6:
	.byte $14, $8d, $19, $8d, $1c, $8d, $20, $9d, $1e, $8d, $48, $15, $8d, $19, $8d, $1c, $8d, $21, $9d, $1e, $8d, $48, $17, $8d
	.byte $1b, $8d, $1e, $8d, $27, $9d, $23, $8d, $48, $25, $8d, $00, $8d, $20, $8d, $00, $8d, $25, $8d, $00, $8d, $48
	.byte $41, $2a
	.word @song0ref6
	.byte $48, $21, $8d, $00
@song0ref59:
	.byte $8d, $21, $8d, $20, $8d, $1e, $8d, $1b, $8d, $48, $df, $48, $20, $8d, $00, $8d, $20, $8d, $1e, $8d, $1c, $8d, $19, $8d
	.byte $48, $df
@song0ref85:
	.byte $48, $1e, $8d, $00, $8d, $1e, $8d, $1c, $8d, $19, $8d, $18, $8d, $48, $9f, $20, $bd
	.byte $41, $08
	.word @song0ref85
	.byte $1e, $8d, $20, $8d, $48, $25, $9d, $00, $9d, $23, $9d, $48, $1c, $9d, $1b, $8d, $1c, $9d, $25, $8d, $48, $23, $bd, $1e
	.byte $9d, $48, $19, $9d, $18, $8d, $19, $9d, $21, $8d, $48, $20, $bd, $1b, $9d, $48, $19, $9d, $18, $8d, $19, $9d, $1c, $8d
	.byte $48, $1b, $9d, $1a, $8d, $1b, $9d, $1e, $8d, $48, $1c, $9d, $1b, $8d, $1e, $9d, $23, $8d, $48, $24, $ad, $27, $ad, $48
	.byte $2c, $8d, $2a, $8d, $28, $8d, $27, $8d, $24, $8d, $20, $8d, $48, $2c, $cd, $00, $8d, $42
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $80
@song0ref199:
	.byte $0d, $dd, $09, $dd, $0b, $dd, $0d, $dd
	.byte $41, $08
	.word @song0ref199
	.byte $00, $dd, $27
@song0ref213:
	.byte $8d, $25, $8d, $27, $8d, $28, $8d, $2a, $8d, $2f, $8d, $00, $dd, $25, $8d, $24
	.byte $41, $09
	.word @song0ref213
	.byte $00, $dd, $20, $8d, $1f, $8d, $20, $8d, $25, $8d, $24, $8d, $27, $8d, $2a, $8d, $29, $8d, $2a, $8d, $2d, $8d, $2c, $8d
	.byte $30, $8d, $31, $9d, $00, $9d, $2f, $9d, $00, $dd, $df, $df, $df, $0d, $dd, $0b, $dd, $09, $dd, $08, $dd, $23
	.byte $41, $09
	.word @song0ref59
	.byte $19, $8d, $1b, $cd, $00, $8d, $42
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $df, $df, $df, $df, $80, $3d, $8d, $3f, $8d, $40, $4c, $8d, $40, $4e, $8d, $40, $4c, $8d, $40, $50, $8d, $40, $53, $8d
	.byte $40, $51, $8d, $40, $50, $8d, $40, $4e, $8d, $40, $4c, $8d, $3f, $8d, $3b, $8d, $39, $8d, $38, $8d, $36, $8d, $39, $8d
	.byte $38, $8d, $36, $85, $00, $85, $36, $85, $00, $85, $38, $85, $00, $85, $38, $85, $00, $85, $3b, $85, $00, $85, $3b, $85
	.byte $00, $85, $21, $8d, $25, $8d, $21, $8d, $25, $8d, $21, $8d, $25, $8d, $23, $8d, $27, $8d, $23, $8d, $27, $8d, $23, $8d
	.byte $27, $8d, $28, $8d, $2a, $8d, $28, $8d, $2a, $8d, $28, $8d, $2a, $8d, $2c, $8d, $2d, $8d, $2c, $8d, $2d, $8d, $2c, $8d
	.byte $2d, $8d, $2a, $8d, $2c, $8d, $2a, $8d, $2c, $8d, $2a, $8d, $2c, $8d, $27, $8d, $2c, $8d, $27, $8d, $2c, $8d, $30, $8d
	.byte $33, $8d, $31, $8d, $30, $8d, $31, $8d, $34, $8d, $33, $8d, $34, $8d, $38, $9d, $00, $9d, $36, $9d, $00, $dd, $36, $85
	.byte $38, $85, $3a, $85, $3b, $85, $3d, $85, $3f, $85, $40, $4d, $85, $40, $4e, $85, $00, $9d, $df, $40, $50, $85, $40, $4f
	.byte $85, $40, $4d, $85, $3f, $85, $3d, $85, $3c, $85, $3a, $85, $38, $85, $00, $9d, $df, $df, $df, $df, $df, $df, $42
	.word @song0ch2loop
@song0ch4:
@song0ch3:
@song0ch3loop:
@song0ref510:
	.byte $df, $df, $df, $df, $df, $df, $df, $df
	.byte $41, $08
	.word @song0ref510
	.byte $41, $08
	.word @song0ref510
	.byte $df, $df, $42
	.word @song0ch3loop
