; This file is for the FamiStudio Sound Engine and was generated by FamiStudio

.export _shoot_sfx=shoot_sfx

shoot_sfx:
	.word @pal
	.word @pal
@pal:
	.word @sfx_pal_song_1

@sfx_pal_song_1:
	.byte $8a,$01,$89,$3f,$01,$8a,$02,$01,$8a,$03,$01,$8a,$04,$01,$8a,$05
	.byte $89,$36,$02,$8a,$06,$01,$8a,$07,$01,$8a,$08,$89,$31,$01,$8a,$09
	.byte $02,$8a,$0a,$01,$8a,$0b,$01,$8a,$0c,$01,$8a,$0d,$03,$00

.export shoot_sfx
